name: Node Setup
description: Checkout repository, setup Node.js and install dependencies
runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: yarn
    - name: Install dependencies
      shell: bash
      run: yarn install
