name: Check
on:
  push:
    branches: [feat/**]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Set Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install deps
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
