name: Check
on:
  push:
    branches:
      - main
      - dev
      - feat/**
      - fix/**
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node and install deps
        uses: ./.github/actions/node-setup
      - name: Lint
        run: yarn lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node and install deps
        uses: ./.github/actions/node-setup
      - name: Test
        run: yarn test
